[device]
identifiers = ["hp_server"]
name = "Server"
manufacturer = "ASUSTeK COMPUTER INC."
model = "PRIME H410M-K"

[temp]
name = "hp_temp"
paths = ["/sys/class/hwmon/hwmon1/", "/sys/class/hwmon/hwmon2/"]
prefixes = ["Package", "Core", "SYSTIN", "CPUTIN"]

[fan]
name = "hp_fan"

[[fan.entities]]
name = "CPU"
pathrpm = "/sys/class/hwmon/hwmon2/fan2_input"

[[fan.entities]]
name = "Case"
pathrpm = "/sys/class/hwmon/hwmon2/fan1_input"
pathpwm = "/sys/class/hwmon/hwmon2/pwm1"
